[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Add redirect rules for backend API calls
[[redirects]]
  from = "/api/*"
  to = "https://qnect-backend.onrender.com/api/:splat"
  status = 200
  force = true
